version: '3.3'

services:
  nginx: 
    image: nginx
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      # - ./nginxcerts:/etc/nginx/certs:ro
      # - ./ids4certs/mineman.ir.key:/etc/nginx/certs/mineman.ir.key:ro
      # - ./ids4certs/mineman.ir.crt:/etc/nginx/certs/mineman.ir.crt:ro
    networks:
      - nginx


networks:
  nginx:
    external: true  
